# These are supported funding model platforms

github: [hongquan]
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
ko_fi: hongquanvn
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: hongquan
# issuehunt: # Replace with a single IssueHunt username
# polar: # Replace with a single Polar username
buy_me_a_coffee: hongquan
# thanks_dev: # Replace with a single thanks.dev username
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

